#!/usr/bin/env python3
"""Imports the Material Symbols Rounded icons of the Cortana Workspace design as vector drawables.

Settings from the design handoff (ICONS.md): weight 300, optical size 24, grade 0; "_fill" = FILL 1.
Usage: python3 tools/import_material_symbols.py name [name_fill ...]   (network needed, dev time only)
The icons are Apache License 2.0 (Google). Each drawable is res/drawable/ms_<name>[_fill].xml.
"""
import os, re, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "app/src/main/res/drawable")
URL = "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded/{name}/{variant}/24px.svg"
TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<!-- Material Symbols Rounded, weight 300, optical size 24 (Apache License 2.0). Generated by tools/import_material_symbols.py. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="960"
    android:viewportHeight="960">
    <group android:translateY="960">
        <path
            android:fillColor="#FFFFFFFF"
            android:pathData="{path}" />
    </group>
</vector>
"""


def fetch(icon: str) -> str:
    name, filled = (icon[:-5], True) if icon.endswith("_fill") else (icon, False)
    svg = urllib.request.urlopen(URL.format(name=name, variant="wght300fill1" if filled else "wght300"), timeout=30).read().decode()
    if 'viewBox="0 -960 960 960"' not in svg or svg.count("<path") != 1:
        raise SystemExit(f"{icon}: unexpected SVG shape")
    return re.search(r'<path d="([^"]+)"', svg).group(1)


if __name__ == "__main__":
    for icon in sys.argv[1:]:
        with open(os.path.join(OUT, f"ms_{icon}.xml"), "w", encoding="utf-8") as f:
            f.write(TEMPLATE.format(path=fetch(icon)))
        print("ms_" + icon)
